var spaceRes = ds_map_create()
ds_map_add(spaceRes, stageResTypes.wall, oSpaceWall)
ds_map_add(spaceRes, stageResTypes.wallSmokeCollider, spSpaceWallCol)
ds_map_add(spaceRes, stageResTypes.floorType, tsSpaceFloor)
ds_map_add(spaceRes, stageResTypes.outside, collisionTileTypes.air)
ds_map_add(spaceRes, stageResTypes.box, oBoxSpace)
ds_map_add(spaceRes, stageResTypes.bedrock, spSpaceBgBd)

var edenRes = ds_map_create()
ds_map_add(edenRes, stageResTypes.wall, oWallEden)
ds_map_add(edenRes, stageResTypes.wallSmokeCollider, spSpaceWallCol)
ds_map_add(edenRes, stageResTypes.floorType, tsFloorEden)
ds_map_add(edenRes, stageResTypes.outside, collisionTileTypes.air)
ds_map_add(edenRes, stageResTypes.box, oBoxEden)
ds_map_add(edenRes, stageResTypes.bedrock, spBgBdEden)

var badlandsRes = ds_map_create()
ds_map_add(badlandsRes, stageResTypes.wall, oWallBadlands)
ds_map_add(badlandsRes, stageResTypes.wallSmokeCollider, spSpaceWallCol)
ds_map_add(badlandsRes, stageResTypes.floorType, tsFloorBadlands)
ds_map_add(badlandsRes, stageResTypes.outside, collisionTileTypes.air)
ds_map_add(badlandsRes, stageResTypes.box, oBoxBadlands)
ds_map_add(badlandsRes, stageResTypes.bedrock, spBgBdBadlands)

var testRes = ds_map_create()
ds_map_add(testRes, stageResTypes.wall, oWallTest)
ds_map_add(testRes, stageResTypes.wallSmokeCollider, spSpaceWallCol)
ds_map_add(testRes, stageResTypes.floorType, tsFloorTest)
ds_map_add(testRes, stageResTypes.outside, collisionTileTypes.air)
ds_map_add(testRes, stageResTypes.box, oBoxTest)
ds_map_add(testRes, stageResTypes.bedrock, spBgBdTest)

//var vrRes = ds_map_create()
//ds_map_add(vrRes, stageResTypes.wall, oWallVR)
//ds_map_add(vrRes, stageResTypes.wallSmokeCollider, spSpaceWallCol)
//ds_map_add(vrRes, stageResTypes.floorType, tsFloorVR)
//ds_map_add(vrRes, stageResTypes.outside, collisionTileTypes.air)
//ds_map_add(vrRes, stageResTypes.box, oBoxVR)

var stageRes = ds_map_create()
ds_map_add_map(stageRes, stageTypes.space, spaceRes)
ds_map_add_map(stageRes, stageTypes.eden, edenRes)
ds_map_add_map(stageRes, stageTypes.test, testRes)
//ds_map_add_map(stageRes, stageTypes.vr, vrRes)
ds_map_add_map(stageRes, stageTypes.badlands, badlandsRes)
return stageRes